# Generated by Django 2.0.1 on 2018-01-31 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('bintroduction', models.CharField(max_length=3000)),
                ('bcomment', models.TextField(default=None)),
            ],
            options={
                'db_table': 'bookname',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clist', models.CharField(max_length=30)),
                ('ccontent', models.TextField()),
                ('cbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShop.BookName')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.AddField(
            model_name='bookname',
            name='cfname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShop.Classification'),
        ),
    ]
